/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Also see :
 * - MS-SSTP : http://msdn.microsoft.com/en-us/library/cc247338(PROT.10).aspx
 *
 */

/* SSTP Properties */
#define SSTP_MIN_LEN 4 
#define SSTP_MAX_ATTR 256


/* SSTP Packet Type */
enum packet_types 
  {
    SSTP_DATA_PACKET = 0x00,
    SSTP_CONTROL_PACKET = 0x01
  };


/* SSTP Protocol Type */
enum sstp_encapsulated_protocol_types 
  {
    SSTP_ENCAPSULATED_PROTOCOL_PPP = 0x0001
  };


/* SSTP Status Message */
enum status_messages 
  {
    SSTP_MSG_CALL_CONNECT_REQUEST = 0x0001,
    SSTP_MSG_CALL_CONNECT_ACK = 0x0002,
    SSTP_MSG_CALL_CONNECT_NAK = 0x0003,
    SSTP_MSG_CALL_CONNECTED = 0x0004,
    SSTP_MSG_CALL_ABORT = 0x0005,
    SSTP_MSG_CALL_DISCONNECT = 0x0006,
    SSTP_MSG_CALL_DISCONNECT_ACK = 0x0007,
    SSTP_MSG_ECHO_REQUEST = 0x0008,
    SSTP_MSG_ECHO_RESPONSE = 0x0009
  };


/* SSTP Attribute Message Type */
enum attr_types 
  {
    SSTP_ATTRIB_NO_ERROR = 0x00,
    SSTP_ATTRIB_ENCAPSULATED_PROTOCOL_ID = 0x01,
    SSTP_ATTRIB_STATUS_INFO = 0x02,
    SSTP_ATTRIB_CRYPTO_BINDING = 0x03,
    SSTP_ATTRIB_CRYPTO_BINDING_REQ = 0x04
  };


/* Crypto Binding Request Attribute */
enum crypto_req_attrs 
  {
    CERT_HASH_PROTOCOL_SHA1 = 0x01,
    CERT_HASH_PROTOCOL_SHA256 = 0x02
  };


/* Status Info Attribute */
enum attr_status 
  {
    ATTRIB_STATUS_NO_ERROR = 0x00000000,
    ATTRIB_STATUS_DUPLICATE_ATTRIBUTE = 0x00000001,
    ATTRIB_STATUS_UNRECOGNIZED_ATTRIBUTE = 0x00000002,
    ATTRIB_STATUS_INVALID_ATTRIB_VALUE_LENGTH = 0x00000003,
    ATTRIB_STATUS_VALUE_NOT_SUPPORTED = 0x00000004,
    ATTRIB_STATUS_UNACCEPTED_FRAME_RECEIVED = 0x00000005,
    ATTRIB_STATUS_RETRY_COUNT_EXCEEDED = 0x00000006,
    ATTRIB_STATUS_INVALID_FRAME_RECEIVED = 0x00000007,
    ATTRIB_STATUS_NEGOTIATION_TIMEOUT = 0x00000008,
    ATTRIB_STATUS_ATTRIB_NOT_SUPPORTED_IN_MSG = 0x00000009,
    ATTRIB_STATUS_REQUIRED_ATTRIBUTE_MISSING = 0x0000000a,
    ATTRIB_STATUS_STATUS_INFO_NOT_SUPPORTED_IN_MSG = 0x0000000b
  };


/* structure definitions */
static const value_string packet_types[] =
  {
    {SSTP_DATA_PACKET, "SSTP Data Packet"},
    {SSTP_CONTROL_PACKET, "SSTP Control Packet"},
    {0, NULL }
  };

static const value_string message_types[] =
  {
    {SSTP_MSG_CALL_CONNECT_REQUEST, "SSTP_MSG_CALL_CONNECT_REQUEST"},
    {SSTP_MSG_CALL_CONNECT_ACK, "SSTP_MSG_CALL_CONNECT_ACK"},
    {SSTP_MSG_CALL_CONNECT_NAK, "SSTP_MSG_CALL_CONNECT_NAK"},
    {SSTP_MSG_CALL_CONNECTED, "SSTP_MSG_CALL_CONNECTED"},
    {SSTP_MSG_CALL_ABORT, "SSTP_MSG_CALL_ABORT"},
    {SSTP_MSG_CALL_DISCONNECT, "SSTP_MSG_CALL_DISCONNECT"},
    {SSTP_MSG_CALL_DISCONNECT_ACK, "SSTP_MSG_CALL_DISCONNECT_ACK"},
    {SSTP_MSG_ECHO_REQUEST, "SSTP_MSG_ECHO_REQUEST" },
    {SSTP_MSG_ECHO_RESPONSE, "SSTP_MSG_ECHO_RESPONSE" },
    {0, NULL }
  };

static const value_string attributes_ids[] =
  {
    {SSTP_ATTRIB_NO_ERROR, "SSTP_ATTRIB_NO_ERROR"},
    {SSTP_ATTRIB_ENCAPSULATED_PROTOCOL_ID, "SSTP_ATTRIB_ENCAPSULATED_PROTOCOL_ID"},
    {SSTP_ATTRIB_STATUS_INFO, "SSTP_ATTRIB_STATUS_INFO"},
    {SSTP_ATTRIB_CRYPTO_BINDING, "SSTP_ATTRIB_CRYPTO_BINDING"},
    {SSTP_ATTRIB_CRYPTO_BINDING_REQ, "SSTP_ATTRIB_CRYPTO_BINDING_REQ"},
    {0, NULL }
  };

static const value_string encapsulated_protocol_id_ids[] =
  {
    { SSTP_ENCAPSULATED_PROTOCOL_PPP, "SSTP_ENCAPSULATED_PROTOCOL_PPP" },
    {0, NULL }
  };

static const value_string hash_protocol_bitmasks[] = 
  {
    {CERT_HASH_PROTOCOL_SHA1, "CERT_HASH_PROTOCOL_SHA1"}, 
    {CERT_HASH_PROTOCOL_SHA256, "CERT_HASH_PROTOCOL_SHA256"},
    {0, NULL }    
  };
      
static const value_string status_info[] =
  {
    {ATTRIB_STATUS_NO_ERROR, "ATTRIB_STATUS_NO_ERROR"},
    {ATTRIB_STATUS_DUPLICATE_ATTRIBUTE, "ATTRIB_STATUS_DUPLICATE_ATTRIBUTE"},
    {ATTRIB_STATUS_UNRECOGNIZED_ATTRIBUTE, "ATTRIB_STATUS_UNRECOGNIZED_ATTRIBUTE"},
    {ATTRIB_STATUS_INVALID_ATTRIB_VALUE_LENGTH, "ATTRIB_STATUS_INVALID_ATTRIB_VALUE_LENGTH"},
    {ATTRIB_STATUS_VALUE_NOT_SUPPORTED, "ATTRIB_STATUS_VALUE_NOT_SUPPORTED"},
    {ATTRIB_STATUS_UNACCEPTED_FRAME_RECEIVED, "ATTRIB_STATUS_UNACCEPTED_FRAME_RECEIVED"}, 
    {ATTRIB_STATUS_RETRY_COUNT_EXCEEDED, "ATTRIB_STATUS_RETRY_COUNT_EXCEEDED"},
    {ATTRIB_STATUS_INVALID_FRAME_RECEIVED, "ATTRIB_STATUS_INVALID_FRAME_RECEIVED"},
    {ATTRIB_STATUS_NEGOTIATION_TIMEOUT, "ATTRIB_STATUS_NEGOTIATION_TIMEOUT"},
    {ATTRIB_STATUS_ATTRIB_NOT_SUPPORTED_IN_MSG, "ATTRIB_STATUS_ATTRIB_NOT_SUPPORTED_IN_MSG"},
    {ATTRIB_STATUS_REQUIRED_ATTRIBUTE_MISSING, "ATTRIB_STATUS_REQUIRED_ATTRIBUTE_MISSING"}, 
    {ATTRIB_STATUS_STATUS_INFO_NOT_SUPPORTED_IN_MSG, "ATTRIB_STATUS_STATUS_INFO_NOT_SUPPORTED_IN_MSG"},
    {0, NULL }
  };

